name: Wails build and release

on:
  push:
    branches: ["*"]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: sorted, platform: linux/amd64, os: ubuntu-latest },
            { name: sorted, platform: windows/amd64, os: windows-latest },
            { name: sorted, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: 1.23
          node-version: 18
          package: false

      # 👇 Upload build artifact per platform
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.platform }}
          path: ./build/bin

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      # Create GitHub release with all artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
