name: Wails Build

on:
  push:
    branches: ["main"] # Trigger on push to main branch
  pull_request:
    branches:
      - "main" # Trigger on pull requests targeting the main branch

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    name: Build and Verify
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - os: ubuntu-22.04
            platform: linux/amd64
          - os: windows-latest
            platform: windows/amd64
          - os: macos-latest
            platform: darwin/universal
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libgirepository1.0-dev \
            libwebkit2gtk-4.0-dev \
            pkg-config

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to path
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Build app with Wails
        run: wails build -platform ${{ matrix.platform }}
