name: Build and Release Sorted App

on:
  push:
    branches: ["*"]
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: sorted
            platform: linux/amd64
            os: ubuntu-latest
          - name: sorted
            platform: windows/amd64
            os: windows-latest
          - name: sorted
            platform: darwin/universal
            os: macos-latest

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build app with Wails
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: 1.21
          node-version: 18
          package: false # Don't make installers (.dmg, .msi, etc.)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.build.platform }}
          path: build/bin

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
