name: Wails Build and Release (Dev Mode)

on:
  push:
    branches: ["*"]
    tags:
      - "v*"
  pull_request:
    branches: [main]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    name: Build and Upload
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            ext: ""
          - os: windows-latest
            platform: windows/amd64
            ext: ".exe"
          - os: macos-latest
            platform: darwin/universal
            ext: ""
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to path
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Build app with Wails
        run: wails build -platform ${{ matrix.platform }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sorted-${{ matrix.platform }}
          path: build/bin/sorted${{ matrix.ext }}

  release:
    name: Create GitHub Release (Dev)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List artifacts
        run: ls -R ./artifacts

      - name: (Skip Release - Just Confirm Artifacts)
        run: echo "Release would happen here. Artifacts downloaded."
