// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { tasks } from '../models';

export function GetAllTasks(): Promise<Array<tasks.Task>>;
